### ISSUE TITLE
Interlock crashed report

### ISSUE THREAD

**Issue by firegrass** [ehazlett/interlock#50]
FYI... happened during (as far as I'm aware) normal operation. Restarting the container brought it back up.

```
time="2015-06-30T14:24:29Z" level="info" msg="[interlock] dispatching event to plugin: name=haproxy version=0.1" 
panic: runtime error: slice bounds out of range

goroutine 28 [running]:
runtime.panic(0x7d5840, 0xc1b2af)
        /usr/src/go/src/pkg/runtime/panic.c:279 +0xf5
main.(*EventHandler).Handle(0xc20802a038, 0xc2083c0000, 0xc208004360, 0x0, 0x0, 0x0)
        /go/src/github.com/ehazlett/interlock/interlock/handler.go:25 +0x296
main.*EventHandler.Handle·fm(0xc2083c0000, 0xc208004360, 0x0, 0x0, 0x0)
        /go/src/github.com/ehazlett/interlock/interlock/manager.go:55 +0x58
github.com/samalba/dockerclient.(*DockerClient).getEvents(0xc2080308a0, 0xc208001100, 0xc208004360, 0x0, 0x0, 0x0)
        /go/src/github.com/ehazlett/interlock/interlock/Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:262 +0x3e0
created by github.com/samalba/dockerclient.(*DockerClient).StartMonitorEvents
        /go/src/github.com/ehazlett/interlock/interlock/Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go:243 +0x83

goroutine 16 [chan receive, 126 minutes]:
main.waitForInterrupt()
        /go/src/github.com/ehazlett/interlock/interlock/commands.go:23 +0x155
main.cmdStart(0xc208062180)
        /go/src/github.com/ehazlett/interlock/interlock/commands.go:88 +0xb0d
github.com/codegangsta/cli.Command.Run(0x827db0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/ehazlett/interlock/interlock/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0xeb2
github.com/codegangsta/cli.(*App).Run(0xc2080272b0, 0xc208004060, 0x6, 0x6, 0x0, 0x0)
        /go/src/github.com/ehazlett/interlock/interlock/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xaea
main.main()
        /go/src/github.com/ehazlett/interlock/interlock/main.go:98 +0x622

goroutine 19 [finalizer wait, 4 minutes]:
runtime.park(0x417a10, 0xc32350, 0xc1d549)
        /usr/src/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xc32350, 0xc1d549)
        /usr/src/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/src/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall, 129 minutes]:
os/signal.loop()
        /usr/src/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /usr/src/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 536 [chan receive, 73 minutes]:
github.com/ehazlett/interlock/plugins/haproxy.func·002()
        /go/src/github.com/ehazlett/interlock/plugins/haproxy/haproxy.go:233 +0x4d
created by github.com/ehazlett/interlock/plugins/haproxy.HaproxyPlugin.Init
        /go/src/github.com/ehazlett/interlock/plugins/haproxy/haproxy.go:241 +0x68


goroutine 1774 [select, 7 minutes]:
net/http.(*persistConn).readLoop(0xc2080ec8f0)
        /usr/src/go/src/pkg/net/http/transport.go:868 +0x829
created by net/http.(*Transport).dialConn
        /usr/src/go/src/pkg/net/http/transport.go:600 +0x93f
```

**Comment by ehazlett** [comment]
What version are you using?  I believe we pushed a fix for this recently.

**Comment by firegrass** [comment]
0.2.3 - I'll update and report back if I can replicate it again. Feel free to close this

**Comment by ehazlett** [comment]
Cool thanks!
